name: Sync Changelog

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MkDocs Repo
        uses: actions/checkout@v3

      - name: Fetch Changelog
        run: |
          curl --fail --show-error -o docs/changelog.md https://raw.githubusercontent.com/I-am-PUID-0/DMB/master/CHANGELOG.md


      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/changelog.md
          git commit -m "Update Changelog" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
